apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
immutable: false
data:
  app.py: |-
    {{ .Files.Get "scripts/app.py" | nindent 8 }}
  requirements.txt: |-
    {{ .Files.Get "scripts/requirements.txt" | nindent 8 }}